Repository Gaming32/world-host, pull requests merged in 2024-12, with the labels that each got.

#148 Add javadocs to the entire plugin system
  src/main/java/io/github/gaming32/worldhost/plugin/FriendAdder.java
  src/main/java/io/github/gaming32/worldhost/plugin/FriendListFriend.java
  src/main/java/io/github/gaming32/worldhost/plugin/InfoTextsCategory.java
  src/main/java/io/github/gaming32/worldhost/plugin/Joinability.java
  src/main/java/io/github/gaming32/worldhost/plugin/OnlineFriend.java
  src/main/java/io/github/gaming32/worldhost/plugin/Profilable.java
  src/main/java/io/github/gaming32/worldhost/plugin/ProfileInfo.java
  src/main/java/io/github/gaming32/worldhost/plugin/WorldHostPlugin.java
Labels: enhancement

#139 Update `ru_ru.json`
  src/main/resources/assets/world-host/lang/ru_ru.json
Labels: enhancement

#149 Port to 1.21.4
  build.gradle.kts
  settings.gradle.kts
  src/main/java/io/github/gaming32/worldhost/gui/screen/AddFriendScreen.java
  src/main/java/io/github/gaming32/worldhost/gui/screen/OnlineFriendsScreen.java
  src/main/java/io/github/gaming32/worldhost/gui/widget/UserListWidget.java
  src/main/java/io/github/gaming32/worldhost/protocol/ProtocolClient.java
  src/main/resources/META-INF/neoforge.mods.toml
  src/main/resources/fabric.mod.json
  version.gradle.kts
  versions/mainProject
Labels: enhancement

#151 Update Gradle and Loom
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#153 Update traditional Chinese translation
  src/main/resources/assets/world-host/lang/zh_tw.json
Labels: enhancement, translation

#154 Bump NeoForge dependency
  version.gradle.kts
Labels: dependencies
